### ISSUE TITLE
Resume

### ISSUE THREAD

**Issue by Code-Hex** [Code-Hex/pget#1]
I'll create resume function

**Comment by vedhavyas** [comment]
Are you already working on it ?

**Comment by Code-Hex** [comment]
@vedhavyas Yes, but I need improvement...

**Comment by vedhavyas** [comment]
@Code-Hex push the changes if you have any, I will make PR with further changes.

One way is to look for sub-parts file size equals the expected size and download the remaining sub parts.

Let me know if you have any alternative. We could also use some info file to store each part details and delete the info file once download is complete.

**Comment by Code-Hex** [comment]
@vedhavyas New commit push now.
PR is welcome. But it is up to the content.

OK. Thanks. I'm very happy.
