### ISSUE TITLE
Support multiple URLs

### ISSUE THREAD

**Issue by Code-Hex** [Code-Hex/pget#11]
For example:

    pget -p 6 http://example.com/i_wnant_file.iso http://example1.com/i_wnant_file.iso http://example2.com/i_wnant_file.iso http://example3.com/i_wnant_file.iso

Introduction To ensure these are the same size. check use md5 if server has md5 hash.

The operation at this,

![untitled diagram](https://cloud.githubusercontent.com/assets/6500104/16718922/4f151912-475f-11e6-9455-ef55a401f55d.png)

I think that It is friendly to the server. but It is very difficult to make.

Please help me. Thank you.

**Comment by vedhavyas** [comment]
@Code-Hex just looking for hash may not be sufficient as there will be cases when hash is not sent through headers. 

My suggestion is to support multiple urls and not to worry about the duplicates as its not the application's concern

**Comment by Code-Hex** [comment]
@vedhavyas That’s right. I think will try to compare at Content-length.

I was not at all thinking it. Nice👍
> My suggestion is to support multiple urls and not to worry about the duplicates as its not the application's concern

**Comment by vedhavyas** [comment]
@Code-Hex will make a PR in next few days

**Comment by Code-Hex** [comment]
@vedhavyas Really!?
I expect for PR. thanks.

**Comment by Code-Hex** [comment]
@vedhavyas Thanks for PR!! Thats great work:+1:
But, I wanted feature which download the same file from multiple mirrors. So, I will PR to @vedhavyas 's PR.
I want to merge it.

Regards.

**Comment by Code-Hex** [comment]
Great!!
Thanks!!
