### ISSUE TITLE
URLにハイフンが3つ続くとエラーが出る

### ISSUE THREAD

**Issue by alice1017** [Code-Hex/pget#13]
日本語で失礼します。
youtubeの動画URLをpgetでダウンロードしてみようと思った所、下記のエラーが出ました。

```text
sh-3.2$ pget -p 6 "https://r6---sn-nvoxu-ioq6.googlevideo.com/videoplayback?sparams=cnr%2Cdur%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm（以下略）"
Error:
  url has not been set in argument
```

原因を探ってみたところ、URLにハイフンが3つ続くとエラーになる模様です。

```text
pget -p 6 "http://r6-snnvoxuioq6.googlevideo.com"
pget -p 6 "http://r6--snnvoxuioq6.googlevideo.com"
```
この場合ですと、ちゃんとホストがないというエラーが出ます。

しかし

```text
pget -p 6 "http://r6---snnvoxuioq6.googlevideo.com"
```

こうなった場合だけ、`Error: url has not been set in argument` となってしまします。

ご対応、よろしくお願いします。

**Comment by Code-Hex** [comment]
@alice1017 報告ありがとうございます。
渡されたURLは外部ライブラリによって正しいURLかチェックされて、正しかったら実行される仕組みとなっています。
なので外部ライブラリの修正をお願いしてみますがしばらく時間がかかるかもしれないです。

**Comment by Code-Hex** [comment]
@alice1017 外部ライブラリへ修正するようにコードも送ったので、反映されたらすぐにアップデートします。https://github.com/asaskevich/govalidator/pull/143

**Comment by alice1017** [comment]
@Code-Hex ご対応ありがとうございます！

**Comment by Code-Hex** [comment]
Done
