### ISSUE TITLE
Not supported range access

### ISSUE THREAD

**Issue by agucova** [Code-Hex/pget#16]
With a lot files, I get this error:
```
pget -p 6 <url>
Checking now <url>
Error:
  not supported range access: <url>
```
By example, this happens when downloading a github repo zip.

I think it may be related with download redirection, wget does just fine.

**Comment by agucova** [comment]
In fact, I'm getting a similar error on aria2c (on similar links)
https://github.com/indexzero/http-server/issues/68
It seems to be related with the Range header.

**Comment by vedhavyas** [comment]
@agucova pget download files from server that support range access. you passed an url that doesn't support range access. Hence, the error.

**Comment by Code-Hex** [comment]
@agucova I agree with @vedhavyas 
Return error since no different from normal downloads If that does not support access.
