### ISSUE TITLE
specify filename

### ISSUE THREAD

**Issue by katabamia** [Code-Hex/pget#18]
Could you add future "Specify filename"?
cause, sometime any webservice return/redirect to time stamped url. (like index.html?t=20161014)
and pget will fail to download this case.

command like this:
`pget -O index.html http://example.com/index.html` // wget like
`pget -f index.html http://example.com/index.html` // friendly-flag? meaning **F**ile

thanks,

**Comment by Code-Hex** [comment]
@katabamia 日本語で大丈夫です！
これは html をダウンロードをしようとして, 名前がおかしくなるっていうことですか？

**Comment by katabamia** [comment]
@Code-Hex 
ファイルをダウンロードする際などに、ファイル拡張子の後ろにタイムスタンプやセッションIDなどをつけ、 `filename.txt?timestamp=20161014&id=hogehogeid` のようにしないとダウンロードできないWebサービスがまれに存在します。
その場合、タイムスタンプ等をつけた状態のURLを使用しなければならなくなるのですが、ファイル名に使用できない文字列を含んでいるとダウンロードに失敗していまいます。

この問題を回避するために、 wget の -O オプションにあたる 保存するファイル名を指定できるオプションを追加してもらえないかという要望です。

**Comment by Code-Hex** [comment]
@katabamia なるほど！
わかりました、修正しますね！

**Comment by Code-Hex** [comment]
@katabamia 対応しました。
https://github.com/Code-Hex/pget/releases/tag/0.0.6
もし大丈夫でしたら、この issue を閉じてください。
宜しくお願いします。

**Comment by katabamia** [comment]
@Code-Hex
対応ありがとうございます。確認しました！
👏
