### ISSUE TITLE
Disable progress bar for scripted applications?

### ISSUE THREAD

**Issue by maddenp** [Code-Hex/pget#19]
I'm evaluating several download-accelerator tools, found pget, and am enjoying working with it. It would be great, however, if there were an option to disable the progress bar, as the output is otherwise difficult to understand when redirected to a logfile. (Ideally, a user could disable _just_ the progress bar, as other basic info and statistics remain quite useful. With some tools, it's all or nothing: You get nothing at all with e.g. a `--quiet` switch, or you get everything, including the log-busting progress bar.)

**Comment by Code-Hex** [comment]
@maddenp Nice Idea.
OK. Plz give me time for a while :+1:

**Comment by Code-Hex** [comment]
I think you can send to `/dev/null`.
so plz try `pget -p6 http://... > /dev/null 2>&1`

**Comment by maddenp** [comment]
Yes, of course I know that I can redirect ALL output to `/dev/null`, but doing so means that I get NO output and, as I said above, "other basic info and statistics remain quite useful". So, of course, feel free to close this request (it's your project), but please be clear that you've decided not to add the (useful, IMO) feature -- not that a solution exists. The request was to disable just the progress bar, not all output.
