### ISSUE TITLE
URL Parsing

### ISSUE THREAD

**Issue by gsquire** [Code-Hex/pget#2]
Instead of a regex as used [here](https://github.com/Code-Hex/pget/blob/bea3b0b20a46bae999f7b63b7594b1e3b60fca5d/pget.go#L158) you can use the [net/url](https://golang.org/pkg/net/url/#Parse) package from the standard library.

**Comment by Code-Hex** [comment]
@gsquire Thanks for teach me.
I've fixed parseURL use [govalidator](https://github.com/asaskevich/govalidator) instead of regex.

commit: https://github.com/Code-Hex/pget/commit/f22c9538d8cdb0b026661f90d584e03d228d2be2

Plz closing issue if you like it.

**Comment by gsquire** [comment]
Cool, nice work 👍
