### ISSUE TITLE
Why must need "Accept-Ranges" header ?

### ISSUE THREAD

**Issue by monotone** [Code-Hex/pget#24]
https://github.com/Code-Hex/pget/blob/9294f7465fa777e5d9400500691e244a9a9ff225/requests.go#L73

**Comment by Arkoprabho** [comment]
This header allows the file to be downloaded in parts. It allows the server to respond to partial requests.
Consider it like you have a 100kB file, and wish to download in 10 parts. 0-10 bytes, 11-20 bytes, 21-30 bytes and so on.
In case the server does accept partial requests, this returns "bytes", else ""
This [link](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Ranges) might help  a bit

**Comment by Code-Hex** [comment]
@monotone @Arkoprabho is Right.

**Comment by monotone** [comment]
@Arkoprabho @Code-Hex   thanks first. 

but when the server not respond this header, `pget` return error like "not supported range access *** ".

`wget` do this all right.    so that`s what I really ask.
