### ISSUE TITLE
Feature request: Add current download speed to progress bar

### ISSUE THREAD

**Issue by luckcolors** [Code-Hex/pget#27]
Hello, It would make easier to understand how fast i'm actually downloading.
We could also use something like https://github.com/dustin/go-humanize to make the downloaded size ,total size and speed more readable.
Let me know what you think.

**Comment by Code-Hex** [comment]
@luckcolors Thanks your feedback!
Probably I implemented you want features at v0.1.0. Could you try this one?
Thanks.
