### ISSUE TITLE
Change the destination to save

### ISSUE THREAD

**Issue by Code-Hex** [Code-Hex/pget#3]
- cannot find the path specified
- change the destination to save

**Comment by vedhavyas** [comment]
@Code-Hex do you want to save the file in a default destination ?

**Comment by LiterallyElvis** [comment]
@Code-Hex do you mean to automatically change the path if the location passed to `-o` can't be found/opened?

**Comment by Code-Hex** [comment]
@LiterallyElvis yes.
So, I'll fix it.

**Comment by Code-Hex** [comment]
Accomplished!! https://github.com/Code-Hex/pget/commit/fcb03834843b052d904f79573bdbb427b2e007a4
